name: Checks
on: [push]
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Checkout
          uses: actions/checkout@v2

        - name: Create .env file
          run: |
            echo DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' >> .env
            echo DEBUG=${{ secrets.DEBUG }} >> .env
            echo DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }} >> .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
        
        - name: Test
          run: docker compose run --rm app sh -c "python manage.py test"

        - name: Lint
          run: docker compose run --rm app sh -c "flake8"    
